// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHZeM3vjEGp7qavaiE5Lu0nugFRiKQOq8',
    appId: '1:1012202195385:web:a9fe36ee8dc43f0fed4e68',
    messagingSenderId: '1012202195385',
    projectId: 'notemanagement-2e014',
    authDomain: 'notemanagement-2e014.firebaseapp.com',
    storageBucket: 'notemanagement-2e014.firebasestorage.app',
    measurementId: 'G-R9CSTD2XQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLh-kFgrNP1JIfLRqFKyqkIA65Ibt1toE',
    appId: '1:1012202195385:android:2bd326b0b6093ee5ed4e68',
    messagingSenderId: '1012202195385',
    projectId: 'notemanagement-2e014',
    storageBucket: 'notemanagement-2e014.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApBYuXYfwuu3ULMn5JMx_dfMxnwE0xfbg',
    appId: '1:1012202195385:ios:a64953df3e2519eaed4e68',
    messagingSenderId: '1012202195385',
    projectId: 'notemanagement-2e014',
    storageBucket: 'notemanagement-2e014.firebasestorage.app',
    iosClientId: '1012202195385-h5a0bvd4stigl8k9ak4qqfqm5s6r9fdv.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApBYuXYfwuu3ULMn5JMx_dfMxnwE0xfbg',
    appId: '1:1012202195385:ios:a64953df3e2519eaed4e68',
    messagingSenderId: '1012202195385',
    projectId: 'notemanagement-2e014',
    storageBucket: 'notemanagement-2e014.firebasestorage.app',
    iosClientId: '1012202195385-h5a0bvd4stigl8k9ak4qqfqm5s6r9fdv.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHZeM3vjEGp7qavaiE5Lu0nugFRiKQOq8',
    appId: '1:1012202195385:web:1fe8d1f1c4850ee3ed4e68',
    messagingSenderId: '1012202195385',
    projectId: 'notemanagement-2e014',
    authDomain: 'notemanagement-2e014.firebaseapp.com',
    storageBucket: 'notemanagement-2e014.firebasestorage.app',
    measurementId: 'G-3MD1NBY80V',
  );
}
